name: chat_chuispt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  flutter:
    sdk: flutter
  mockito: ^5.3.2
  firebase_database_mocks: ^0.6.0
  provider: ^6.0.5
  flutter_keyboard_size: ^1.0.1
  firebase_auth: ^4.3.0
  google_sign_in: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
