name: chat_chuispt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  flutter:
    sdk: flutter
  mockito: ^5.3.2
  firebase_database_mocks: ^0.6.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
